# """Service for generating ServiceNow background scripts"""
# from services.type_resolver import resolve_type, get_sn_internal_type
# from models import FieldRow


# class ScriptGenerator:
#     """Generates ServiceNow background scripts for field configuration"""
    
#     def __init__(self):
#         pass
    
#     def generate_background_script(self, table_name: str, fields: list[FieldRow]) -> str:
#         """Generate a background script for updating field definitions"""
#         tbl = table_name or "x_custom_table"
#         lines = []
        
#         lines += [
#             "// ServiceNow Background Script - Multi-Language Field Labels",
#             f"// Table: {tbl}",
#             "// Auto-generated by SN Field Script Generator",
#             "// Creates language-specific labels: English (en) and Japanese (ja)",
#             "// Users see labels based on their language preference",
#             "",
#             f"var tableName = '{tbl}';",
#             "",
#         ]
        
#         for field in fields:
#             if not field.field_name:
#                 continue
#             lines += self._generate_field_script(tbl, field)
        
#         lines.append(f"gs.info('Script execution complete for table: ' + tableName);")
#         return "\n".join(lines)
    
#     def generate_update_set_script(self, table_name: str, fields: list[FieldRow]) -> str:
#         """Generate an update set script for field configuration"""
#         tbl = table_name or "x_custom_table"
#         lines = []
        
#         lines += [
#             "// ServiceNow Update Set Script - Multi-Language Field Labels",
#             f"// Table: {tbl}",
#             "// Creates language-specific labels: English (en) and Japanese (ja)",
#             "",
#         ]
        
#         for field in fields:
#             if not field.field_name:
#                 continue
#             lines += self._generate_update_set_field_script(tbl, field)
        
#         return "\n".join(lines)
    
#     def _generate_field_script(self, table_name: str, field: FieldRow) -> list:
#         """Generate script lines for a single field"""
#         res = resolve_type(field.data_type)
#         sn_type = get_sn_internal_type(res)
        
#         comment = f"// Field: {field.field_name}"
#         if field.label or field.english_label:
#             labels = []
#             if field.english_label:
#                 labels.append(field.english_label)
#             if field.label:
#                 labels.append(field.label)
#             comment += f" ({' / '.join(labels)})"
        
#         lines = [
#             comment,
#             "(function() {",
#             "  try {",
#             "    var gr = new GlideRecord('sys_dictionary');",
#             f"    gr.addQuery('name', tableName);",
#             f"    gr.addQuery('element', '{field.field_name}');",
#             "    gr.query();",
#             "    if (gr.next()) {",
#             f"      gr.setValue('internal_type', '{sn_type}');",
#         ]
        
#         if res.get("max_len"):
#             lines.append(f"      gr.setValue('max_length', {res['max_len']});")
#         if res.get("scale"):
#             lines.append(f"      gr.setValue('attributes', 'scale={res['scale']}');")
#         if field.default_value:
#             lines.append(f"      gr.setValue('default_value', '{field.default_value}');")
        
#         lines += [
#             "      gr.update();",
#             f"      gs.info('Updated sys_dictionary: ' + tableName + '.{field.field_name}');",
#         ]
        
#         # English label
#         if field.english_label:
#             escaped_en_label = field.english_label.replace("'", "\\'")
#             lines += self._generate_language_label_script(
#                 "en", escaped_en_label, field.field_name, "English"
#             )
        
#         # Japanese label
#         if field.label:
#             escaped_ja_label = field.label.replace("'", "\\'")
#             lines += self._generate_language_label_script(
#                 "ja", escaped_ja_label, field.field_name, "Japanese"
#             )
        
#         lines += [
#             "    } else {",
#             f"      gs.warn('Field not found: ' + tableName + '.{field.field_name}');",
#             "    }",
#             "  } catch (e) {",
#             f"    gs.error('Error processing field {field.field_name}: ' + e.message);",
#             "  }",
#             "})();",
#             "",
#         ]
        
#         return lines
    
#     def _generate_language_label_script(self, lang: str, label: str, field_name: str, lang_name: str) -> list:
#         """Generate script for language-specific label"""
#         lang_var = "enDoc" if lang == "en" else "jaDoc"
#         return [
#             "",
#             f"      // Create/Update {lang_name} label in sys_documentation",
#             f"      var {lang_var} = new GlideRecord('sys_documentation');",
#             f"      {lang_var}.addQuery('name', tableName);",
#             f"      {lang_var}.addQuery('element', '{field_name}');",
#             f"      {lang_var}.addQuery('language', '{lang}');",
#             f"      {lang_var}.query();",
#             f"      if ({lang_var}.next()) {{",
#             f"        {lang_var}.label = '{label}';",
#             f"        {lang_var}.update();",
#             f"        gs.info('Updated {lang_name} label for {field_name}');",
#             f"      }} else {{",
#             f"        {lang_var}.newRecord();",
#             f"        {lang_var}.name = tableName;",
#             f"        {lang_var}.element = '{field_name}';",
#             f"        {lang_var}.language = '{lang}';",
#             f"        {lang_var}.label = '{label}';",
#             f"        {lang_var}.plural = '';",
#             f"        {lang_var}.insert();",
#             f"        gs.info('Created {lang_name} label for {field_name}');",
#             f"      }}",
#         ]
    
#     def _generate_update_set_field_script(self, table_name: str, field: FieldRow) -> list:
#         """Generate update set script lines for a single field"""
#         res = resolve_type(field.data_type)
#         sn_type = get_sn_internal_type(res)
        
#         label_display = ""
#         if field.english_label:
#             label_display = field.english_label
#         if field.label:
#             label_display += f" ({field.label})" if label_display else field.label
        
#         lines = [
#             f"// {field.field_name} - {label_display}",
#             "(function() {",
#             "  var el = new GlideRecord('sys_dictionary');",
#             f"  el.addQuery('name', '{table_name}');",
#             f"  el.addQuery('element', '{field.field_name}');",
#             "  el.query();",
#             "  if (el.next()) {",
#             f"    el.internal_type = '{sn_type}';",
#         ]
        
#         if res.get("max_len"):
#             lines.append(f"    el.max_length = {res['max_len']};")
#         if field.default_value:
#             lines.append(f"    el.default_value = '{field.default_value}';")
        
#         lines.append("    el.update();")
        
#         # English label
#         if field.english_label:
#             escaped_en_label = field.english_label.replace("'", "\\'")
#             lines += [
#                 "",
#                 "    // English label",
#                 "    var enDoc = new GlideRecord('sys_documentation');",
#                 "    enDoc.addQuery('name', el.name);",
#                 "    enDoc.addQuery('element', el.element);",
#                 "    enDoc.addQuery('language', 'en');",
#                 "    enDoc.query();",
#                 "    if (enDoc.next()) {",
#                 f"      enDoc.label = '{escaped_en_label}';",
#                 "      enDoc.update();",
#                 "    } else {",
#                 "      enDoc.newRecord();",
#                 "      enDoc.name = el.name;",
#                 "      enDoc.element = el.element;",
#                 "      enDoc.language = 'en';",
#                 f"      enDoc.label = '{escaped_en_label}';",
#                 "      enDoc.insert();",
#                 "    }",
#             ]
        
#         # Japanese label
#         if field.label:
#             escaped_ja_label = field.label.replace("'", "\\'")
#             lines += [
#                 "",
#                 "    // Japanese label",
#                 "    var jaDoc = new GlideRecord('sys_documentation');",
#                 "    jaDoc.addQuery('name', el.name);",
#                 "    jaDoc.addQuery('element', el.element);",
#                 "    jaDoc.addQuery('language', 'ja');",
#                 "    jaDoc.query();",
#                 "    if (jaDoc.next()) {",
#                 f"      jaDoc.label = '{escaped_ja_label}';",
#                 "      jaDoc.update();",
#                 "    } else {",
#                 "      jaDoc.newRecord();",
#                 "      jaDoc.name = el.name;",
#                 "      jaDoc.element = el.element;",
#                 "      jaDoc.language = 'ja';",
#                 f"      jaDoc.label = '{escaped_ja_label}';",
#                 "      jaDoc.insert();",
#                 "    }",
#             ]
        
#         lines += ["  }", "})();", ""]
#         return lines

"""Service for generating ServiceNow background scripts"""
from services.type_resolver import resolve_type, get_sn_internal_type
from models import FieldRow


class ScriptGenerator:
    """Generates ServiceNow background scripts for field configuration"""

    def generate_background_script(self, table_name: str, fields: list[FieldRow]) -> str:
        """Generate a background script for updating field definitions"""
        table = table_name or "x_custom_table"
        lines = [
            "// ServiceNow Background Script - Multi-Language Field Labels",
            f"// Table: {table}",
            "// Auto-generated by SN Field Script Generator",
            "// Creates language-specific labels: English (en) and Japanese (ja)",
            "// Users see labels based on their language preference",
            "",
            f"var tableName = '{table}';",
            "",
        ]

        for field in fields:
            if field.field_name:
                lines += self._generate_field_block(table, field)

        lines.append(f"gs.info('Script execution complete for table: ' + tableName);")
        return "\n".join(lines)

    def generate_update_set_script(self, table_name: str, fields: list[FieldRow]) -> str:
        """Generate an update set script for field configuration"""
        table = table_name or "x_custom_table"
        lines = [
            "// ServiceNow Update Set Script - Multi-Language Field Labels",
            f"// Table: {table}",
            "// Creates language-specific labels: English (en) and Japanese (ja)",
            "",
        ]

        for field in fields:
            if field.field_name:
                lines += self._generate_update_set_field_block(table, field)

        return "\n".join(lines)

    def _generate_field_block(self, table_name: str, field: FieldRow) -> list:
        """Generate background script lines for a single field"""
        resolved_type = resolve_type(field.data_type)
        sn_internal_type = get_sn_internal_type(resolved_type)

        comment = f"// Field: {field.field_name}"
        if field.label:
            comment += f" ({field.label})"

        lines = [
            comment,
            "(function() {",
            "  try {",
            "    var dictRecord = new GlideRecord('sys_dictionary');",
            f"    dictRecord.addQuery('name', tableName);",
            f"    dictRecord.addQuery('element', '{field.field_name}');",
            "    dictRecord.query();",
            "    if (dictRecord.next()) {",
            f"      dictRecord.setValue('internal_type', '{sn_internal_type}');",
        ]

        if resolved_type.get("max_len"):
            lines.append(f"      dictRecord.setValue('max_length', {resolved_type['max_len']});")
        if resolved_type.get("scale"):
            lines.append(f"      dictRecord.setValue('attributes', 'scale={resolved_type['scale']}');")
        if field.default_value:
            lines.append(f"      dictRecord.setValue('default_value', '{field.default_value}');")

        lines += [
            "      dictRecord.update();",
            f"      gs.info('Updated sys_dictionary: ' + tableName + '.{field.field_name}');",
        ]

        if field.label:
            escaped_label = field.label.replace("'", "\\'")
            lines += self._generate_label_upsert_block("en", escaped_label, field.field_name, "English")

        lines += [
            "    } else {",
            f"      gs.warn('Field not found: ' + tableName + '.{field.field_name}');",
            "    }",
            "  } catch (e) {",
            f"    gs.error('Error processing field {field.field_name}: ' + e.message);",
            "  }",
            "})();",
            "",
        ]

        return lines

    def _generate_label_upsert_block(self, lang: str, label: str, field_name: str, lang_name: str) -> list:
        """Generate script lines to create or update a label in sys_documentation"""
        doc_var = "labelDoc"
        return [
            "",
            f"      // Create/Update {lang_name} label in sys_documentation",
            f"      var {doc_var} = new GlideRecord('sys_documentation');",
            f"      {doc_var}.addQuery('name', tableName);",
            f"      {doc_var}.addQuery('element', '{field_name}');",
            f"      {doc_var}.addQuery('language', '{lang}');",
            f"      {doc_var}.query();",
            f"      if ({doc_var}.next()) {{",
            f"        {doc_var}.label = '{label}';",
            f"        {doc_var}.plural = '{label}';",
            f"        {doc_var}.update();",
            f"        gs.info('Updated {lang_name} label for {field_name}');",
            f"      }} else {{",
            f"        {doc_var}.newRecord();",
            f"        {doc_var}.name = tableName;",
            f"        {doc_var}.element = '{field_name}';",
            f"        {doc_var}.language = '{lang}';",
            f"        {doc_var}.label = '{label}';",
            f"        {doc_var}.plural = '{label}';",
            f"        {doc_var}.insert();",
            f"        gs.info('Created {lang_name} label for {field_name}');",
            f"      }}",
        ]

    def _generate_update_set_field_block(self, table_name: str, field: FieldRow) -> list:
        """Generate update set script lines for a single field"""
        resolved_type = resolve_type(field.data_type)
        sn_internal_type = get_sn_internal_type(resolved_type)

        label_display = field.label or ""

        lines = [
            f"// {field.field_name} - {label_display}",
            "(function() {",
            "  var dictRecord = new GlideRecord('sys_dictionary');",
            f"  dictRecord.addQuery('name', '{table_name}');",
            f"  dictRecord.addQuery('element', '{field.field_name}');",
            "  dictRecord.query();",
            "  if (dictRecord.next()) {",
            f"    dictRecord.internal_type = '{sn_internal_type}';",
        ]

        if resolved_type.get("max_len"):
            lines.append(f"    dictRecord.max_length = {resolved_type['max_len']};")
        if field.default_value:
            lines.append(f"    dictRecord.default_value = '{field.default_value}';")

        lines.append("    dictRecord.update();")

        if field.label:
            escaped_label = field.label.replace("'", "\\'")
            lines += [
                "",
                "    // English label",
                "    var labelDoc = new GlideRecord('sys_documentation');",
                "    labelDoc.addQuery('name', dictRecord.name);",
                "    labelDoc.addQuery('element', dictRecord.element);",
                "    labelDoc.addQuery('language', 'en');",
                "    labelDoc.query();",
                "    if (labelDoc.next()) {",
                f"      labelDoc.label = '{escaped_label}';",
                "      labelDoc.update();",
                "    } else {",
                "      labelDoc.newRecord();",
                "      labelDoc.name = dictRecord.name;",
                "      labelDoc.element = dictRecord.element;",
                "      labelDoc.language = 'en';",
                f"      labelDoc.label = '{escaped_label}';",
                "      labelDoc.insert();",
                "    }",
            ]

        lines += ["  }", "})();", ""]
        return lines