# Domain Name → ServiceNow type mapping
DOMAIN_MAP = {
    "YYYY":              {"type": "String",    "max_len": 4},
    "YYYYMM":            {"type": "String",    "max_len": 6},
    "YYYYMMDD":          {"type": "Date"},
    "MASTER_DATE":       {"type": "Date"},
    "UPDATE_DATE":       {"type": "Date/Time"},
    "YEN_HM":            {"type": "Integer"},
    "YEN_M":             {"type": "Long",      "max_len": 9},
    "YEN_TH":            {"type": "Long"},
    "YEN":               {"type": "Long"},
    "SEKISU":            {"type": "String"},
    "RATE_RATIO_S":      {"type": "Decimal",   "max_len": 6, "scale": 3},
    "RATE_RATIO_Z":      {"type": "Decimal",   "max_len": 8, "scale": 3},
    "FLG":               {"type": "True/False"},
    "STATE":             {"type": "String",    "max_len": 1},
    "TYPE":              {"type": "String",    "max_len": 1},
    "NUM_OF":            {"type": "Integer"},
    "NUM_OF_DP":         {"type": "Decimal",   "max_len": 9, "scale": 1},
    "AREA_CODE":         {"type": "String",    "max_len": 2},
    "CUSTOMER_CODE":     {"type": "String",    "max_len": 10},
    "OFFICE_CODE":       {"type": "String",    "max_len": 6},
    "KAMOKU_CODE":       {"type": "String",    "max_len": 4},
    "TYOHO_KAMOKU_CODE": {"type": "String",    "max_len": 7},
    "KAMOKU_TYPE_CODE":  {"type": "String",    "max_len": 4},
    "GROUP_CODE":        {"type": "String",    "max_len": 3},
    "PROCESS_CYCLE":     {"type": "String",    "max_len": 2},
    "KAMOKU_NAME":       {"type": "String",    "max_len": 60},
    "SHINREN_NAME":      {"type": "String",    "max_len": 30},
    "SEQ_NO":            {"type": "Integer"},
    "CHECK_RULE":        {"type": "String",    "max_len": 2},
    "SUM_RULE":          {"type": "String",    "max_len": 1},
    "DANTAI":            {"type": "String",    "max_len": 1},
    "HYOU":              {"type": "String",    "max_len": 2},
    "PAGE":              {"type": "String",    "max_len": 3},
    "GYOU":              {"type": "String",    "max_len": 3},
    "RETSU":             {"type": "String",    "max_len": 5},
}

# ServiceNow internal type mapping
SN_TYPE_MAP = {
    "String":     "string",
    "Integer":    "integer",
    "Long":       "long_integer",
    "Decimal":    "decimal",
    "Date":       "glide_date",
    "Date/Time":  "glide_date_time",
    "True/False": "boolean",
}
